"""Read pipeline result JSONs and emit LaTeX macros for the paper."""
import sys, os, json
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import numpy as np
from io_utils import load_results

encoding = load_results(snakemake.input.encoding)
rsa = load_results(snakemake.input.rsa)
dynamics = load_results(snakemake.input.dynamics)
pca = load_results(snakemake.input.pca)
config = snakemake.config

# --- helpers ---

def fmt(value, decimals=2):
    """Format a number, stripping trailing zeros."""
    return f"{value:.{decimals}f}"

def pct(value):
    return f"{value * 100:.1f}"

macros = {}

def add(name, value):
    macros[name] = value

# --- config ---
add("nScenes", str(config["n_scenes"]))
add("nNeurons", str(config["n_neurons"]))
add("imageSize", str(config["image_size"]))
add("noiseLevel", fmt(config["noise_level"]))
add("nTimesteps", str(config["n_timesteps"]))
add("rsaSubsample", str(config["rsa_subsample"]))

# --- encoding ---
r2_pixels = np.array(encoding["r2_pixels_only"])
r2_combined = np.array(encoding["r2_combined"])
delta_r2 = np.array(encoding["delta_r2"])

add("encodingRsqPixels", fmt(np.mean(r2_pixels), 4))
add("encodingRsqCombined", fmt(np.mean(r2_combined), 4))
add("encodingDeltaRsq", fmt(np.mean(delta_r2), 4))
add("controlAccuracy", pct(encoding["control_accuracy"]))

# --- RSA ---
add("rsaCorrNeuralRender", fmt(rsa["corr_neural_render"], 4))
add("rsaCorrNeuralPhysics", fmt(rsa["corr_neural_physics"], 4))
add("rsaCorrRenderPhysics", fmt(rsa["corr_render_physics"], 4))
add("rsaPartialNeuralPhysics", fmt(rsa["partial_neural_physics"], 4))
add("rsaRatio", fmt(rsa["corr_neural_render"] / max(rsa["corr_neural_physics"], 1e-9), 1))

# --- dynamics ---
r2_phys_fwd = np.array(dynamics["r2_physics_forward"])
r2_pix_fwd = np.array(dynamics["r2_pixel_forward"])

add("dynamicsRsqPhysics", fmt(np.mean(r2_phys_fwd), 4))
add("dynamicsRsqPixel", fmt(np.mean(r2_pix_fwd), 4))
add("dynamicsGap", fmt(np.mean(r2_phys_fwd) - np.mean(r2_pix_fwd), 4))

# --- PCA ---
cumvar = np.array(pca["cumulative_variance"])
for k in [1, 5, 10, 50]:
    if k <= len(cumvar):
        add(f"pcaVarExplained{k}", pct(cumvar[k - 1]))

# --- evaluation summary ---
evaluation = load_results(snakemake.input.evaluation)
add("evalPassed", str(evaluation["n_passed"]))
add("evalTotal", str(evaluation["n_total"]))

# --- write ---
out = snakemake.output[0]
with open(out, "w") as f:
    f.write("% Auto-generated by gen_macros.py -- do not edit by hand\n")
    for name, value in macros.items():
        f.write(f"\\newcommand{{\\{name}}}{{{value}}}\n")
