"""Read pipeline result JSONs and emit LaTeX macros for the paper."""
import sys, os, json
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import numpy as np
from io_utils import load_results

encoding = load_results(snakemake.input.encoding)
rsa = load_results(snakemake.input.rsa)
dynamics = load_results(snakemake.input.dynamics)
pca = load_results(snakemake.input.pca)
config = snakemake.config

# --- helpers ---

def fmt(value, decimals=2):
    """Format a number, stripping trailing zeros."""
    return f"{value:.{decimals}f}"

def pct(value):
    return f"{value * 100:.1f}"

def latex_int(n):
    """Format integer with LaTeX thousands separators: 49152 -> '49{,}152'."""
    s = str(n)
    parts = []
    while len(s) > 3:
        parts.append(s[-3:])
        s = s[:-3]
    parts.append(s)
    return "{,}".join(reversed(parts))

macros = {}

def add(name, value):
    macros[name] = value

# --- config ---
add("nScenes", str(config["n_scenes"]))
add("nNeurons", str(config["n_neurons"]))
add("imageSize", str(config["image_size"]))
add("noiseLevel", fmt(config["noise_level"]))
add("nTimesteps", str(config["n_timesteps"]))
add("rsaSubsample", str(config["rsa_subsample"]))

# --- dimensions (computed from config) ---
image_size = config["image_size"]
n_objects = config["n_objects"]
n_brain_frames = 3  # initial / early / late, all full RGBA+depth+seg
d_render = n_brain_frames * image_size * image_size * 12  # 3 frames × (RGBA(4) + depth(4) + seg(4)) raw bytes, each cast to float32
d_physics_per_obj = 16  # pos(3) + orn(4) + lin_vel(3) + ang_vel(3) + mass(1) + friction(1) + x_accel(1)
d_config_per_obj = 9    # shape_is_box(1) + radius(1) + half_extents(3) + color(4)
d_physics = d_physics_per_obj * n_objects
d_config = d_config_per_obj * n_objects
d_total = d_render + d_physics + d_config

add("nObjects", str(n_objects))
add("dRender", latex_int(d_render))
add("dPhysics", str(d_physics))
add("dConfig", str(d_config))
add("dTotal", latex_int(d_total))
add("dPhysicsPerObject", str(d_physics_per_obj))
add("dConfigPerObject", str(d_config_per_obj))

# --- encoding ---
r2_pixel = np.array(encoding["r2_pixel_only"])
r2_combined = np.array(encoding["r2_combined"])
delta_r2 = np.array(encoding["delta_r2"])

add("encodingRsqPixel", fmt(np.mean(r2_pixel), 4))
add("encodingRsqCombined", fmt(np.mean(r2_combined), 4))
add("encodingDeltaRsq", fmt(np.mean(delta_r2), 4))
add("controlAccuracy", pct(encoding["control_accuracy"]))

# --- RSA ---
add("rsaCorrNeuralPixel", fmt(rsa["corr_neural_pixel"], 4))
add("rsaCorrNeuralPhysics", fmt(rsa["corr_neural_physics"], 4))
add("rsaCorrPixelPhysics", fmt(rsa["corr_pixel_physics"], 4))
add("rsaPartialNeuralPhysics", fmt(rsa["partial_neural_physics"], 4))
add("rsaRatio", fmt(rsa["corr_neural_pixel"] / max(rsa["corr_neural_physics"], 1e-9), 1))

# --- dynamics ---
r2_phys_fwd = np.array(dynamics["r2_physics_forward"])
r2_pix_fwd = np.array(dynamics["r2_pixel_forward"])

add("dynamicsRsqPhysics", fmt(np.mean(r2_phys_fwd), 4))
add("dynamicsRsqPixel", fmt(np.mean(r2_pix_fwd), 4))
add("dynamicsGap", fmt(np.mean(r2_phys_fwd) - np.mean(r2_pix_fwd), 4))

# --- PCA ---
cumvar = np.array(pca["cumulative_variance"])
for k, label in [(1, "One"), (5, "Five"), (10, "Ten"), (50, "Fifty")]:
    if k <= len(cumvar):
        add(f"pcaVarExplained{label}", pct(cumvar[k - 1]))

pc_counts = pca["pc_counts"]
decode_accs = pca["decode_accs_per_target"]["motion_dir"]

# Decoding accuracy at specific PC counts
for k, label in [(5, "Five"), (10, "Ten")]:
    if k in pc_counts:
        idx = pc_counts.index(k)
        add(f"pcaDecodeTop{label}", pct(decode_accs[idx]))

# First PC count where motion decoding exceeds 60%
for k, acc in zip(pc_counts, decode_accs):
    if acc > 0.60:
        add("pcaDecodeThresholdK", str(k))
        add("pcaDecodeThresholdAcc", pct(acc))
        add("pcaDecodeThresholdVar", pct(cumvar[k - 1]))
        break

# --- evaluation summary ---
evaluation = load_results(snakemake.input.evaluation)
add("evalPassed", str(evaluation["n_passed"]))
add("evalTotal", str(evaluation["n_total"]))

# --- write ---
out = snakemake.output[0]
with open(out, "w") as f:
    f.write("% Auto-generated by gen_macros.py -- do not edit by hand\n")
    for name, value in macros.items():
        f.write(f"\\newcommand{{\\{name}}}{{{value}}}\n")
